@startuml
'https://plantuml.com/class-diagram

class MascotaVirtual {
    - estado: EstadoMascota
    + comer()
    + jugar()

    + MascotaVirtual(estadoInicial: EstadoMascota)
    + cambiarEstado(estado: EstadoMascota)
}

abstract class EstadoMascota {
    # mascota: MascotaVirtual

    + comer()
    + jugar()
    + cambiarEstado(estado: EstadoMascota)
}

class Hambrienta extends EstadoMascota {
    + comer()
    + jugar()
}

class Contenta extends EstadoMascota {
    - nivelContenta: int

    + comer()
    + jugar()
}

class Aburrida extends EstadoMascota {
    + comer()
    + jugar()
}

'relaciones

MascotaVirtual o-r-> EstadoMascota


@enduml