@startuml
'https://plantuml.com/class-diagram

skinparam Linetype ortho
title "Ejercicio 34"

class Banco {
    - nombre: string
    - empleados: List<Aprobador>
    + agregarAprobador(empleado: Aprobador) : void
    + aprobarPrestamo(prestamo: Prestamo) : boolean
}

abstract class Aprobador {
    - maximoAprobar: int = 0;

    + aprobar(prestamo : Prestamo) : boolean
}

note right of Aprobador::aprobar
    public boolean aprobar(prestamo) {
        return prestamo.monto <= maximoAprobar;
    }
end note

class Prestamo {
    - monto: int
}

class Empleado extends Aprobador {
    - maximoAprobar: int

    + aprobar(prestamo : Prestamo) : boolean
}

note bottom of Empleado
    maximoAprobar = 10000
end note

class Supervisor extends Aprobador {
    - maximoAprobar: int

    + aprobar(prestamo : Prestamo) : boolean
}

note bottom of Supervisor
    maximoAprobar = 40000
end note

class Gerente extends Aprobador {
    - maximoAprobar: int

    + aprobar(prestamo : Prestamo) : boolean
}

note bottom of Gerente
    maximoAprobar = 120000
end note

'relaciones
Banco o-- Aprobador
Aprobador o-l- Prestamo

@enduml